# Generated by Django 4.2.4 on 2023-08-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='project_thumbnails')),
                ('diagram', models.ImageField(upload_to='project_diagrams')),
                ('links', models.JSONField()),
                ('description', models.TextField()),
                ('frontend', models.JSONField()),
                ('backend', models.JSONField()),
                ('database', models.JSONField()),
                ('host', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='resume')),
                ('image', models.ImageField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.JSONField()),
            ],
        ),
    ]
