# Generated by Django 4.2.4 on 2023-08-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('id',), 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Resume'},
        ),
        migrations.AlterModelOptions(
            name='socials',
            options={'verbose_name_plural': 'Socials'},
        ),
        migrations.AddField(
            model_name='projects',
            name='tools',
            field=models.JSONField(default=['']),
            preserve_default=False,
        ),
    ]
