# Generated by Django 4.2.4 on 2023-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projects_options_alter_resume_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField()),
                ('socials', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Socials',
            },
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
