# Generated by Django 4.2.4 on 2023-09-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aboutme_delete_socials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About Me'},
        ),
    ]
