# Generated by Django 4.2.4 on 2023-09-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aboutme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='diagram',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.BinaryField(),
        ),
    ]
