# Generated by Django 4.2.4 on 2023-09-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_projects_diagram_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to='page/static/media/resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='page/static/media/resume'),
        ),
    ]
