# Generated by Django 4.2.4 on 2023-09-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resume_image_alter_resume_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='diagram',
            field=models.ImageField(upload_to='page/static/media'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='page/static/media'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to='page/static/media'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to='page/static/media'),
        ),
    ]
