# Generated by Django 4.2.4 on 2023-09-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_projects_diagram_alter_projects_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='diagram',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
