# Generated by Django 4.2.4 on 2023-10-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_projects_diagram_alter_projects_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
