# Generated by Django 5.0.1 on 2024-02-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('company', models.CharField(max_length=75)),
                ('title', models.CharField(max_length=75)),
                ('length', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('tech', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
