# Generated by Django 5.0.1 on 2024-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
