# Generated by Django 5.0.1 on 2024-02-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_projects_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='diagram',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.URLField(),
        ),
    ]
