# Generated by Django 5.0.1 on 2024-02-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_experience_image_alter_projects_diagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='socials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='tech_stack',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tech',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='backend',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='database',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='frontend',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='host',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='links',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tools',
            field=models.TextField(),
        ),
    ]
